package com.linkit.team_rostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shift implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private com.linkit.team_rostering.Timeslot timeslot;
    private com.linkit.team_rostering.Skill requiredSkill;

    public Shift() {
    }

    public com.linkit.team_rostering.Timeslot getTimeslot() {
        return this.timeslot;
    }

    public void setTimeslot( com.linkit.team_rostering.Timeslot timeslot ) {
        this.timeslot = timeslot;
    }

    public com.linkit.team_rostering.Skill getRequiredSkill() {
        return this.requiredSkill;
    }

    public void setRequiredSkill(
            com.linkit.team_rostering.Skill requiredSkill ) {
        this.requiredSkill = requiredSkill;
    }

    public Shift( com.linkit.team_rostering.Timeslot timeslot,
                  com.linkit.team_rostering.Skill requiredSkill ) {
        this.timeslot = timeslot;
        this.requiredSkill = requiredSkill;
    }

}