package com.linkit.team_rostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Team implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String name;
    private java.util.List<com.linkit.team_rostering.Skill> skillList;
    private java.util.List<com.linkit.team_rostering.Employee> employeeList;

    public java.lang.String getName() {
        return name;
    }

    public void setName( java.lang.String name ) {
        this.name = name;
    }
    
    public Team() {
    }

    public Team( java.lang.String name,
                     java.util.List<com.linkit.team_rostering.Skill> skillList,
                     java.util.List<com.linkit.team_rostering.Employee> employeeList) {
        this.name = name;
        this.skillList = skillList;
        this.employeeList = employeeList;
    }
    
    public java.util.List<com.linkit.team_rostering.Employee> getEmployeeList() {
        return this.employeeList;
    }
    
    public void setEmployeeList(
            java.util.List<com.linkit.team_rostering.Employee> employeeList) {
        this.employeeList = employeeList;
    }

    public java.util.List<com.linkit.team_rostering.Skill> getSkillList() {
        return this.skillList;
    }

    public void setSkillList(java.util.List<com.linkit.team_rostering.Skill> skillList){
        this.skillList = skillList;
    }


}