package com.linkit.trostering;

import java.lang.Number;

rule "DayOffRequest"
	dialect "mvel"
	when
		$dayOffRequest : DayOffRequest( )
		$team: Team()
		ShiftAssignment( $team.employeeList contains ( $dayOffRequest.employee ) , shift.timeslot.startTime.toLocalDate() == $dayOffRequest.date.toLocalDate() )
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -$dayOffRequest.weight.intValue());
        // System.out.println("DayOffRequest D:"  + $dayOffRequest.date.toLocalDate() + " for E(-"+ $dayOffRequest.weight +"):" + $dayOffRequest.employee.name + " T:" + $team.name);
end




